keyboard:
  matrix_positions:
    - [[2,1], [3,1], [4,1], [5,1], [6,1],                  [13,1], [14,1], [15,1], [16,1], [17,1]]
    - [[2,2], [3,2], [4,2], [5,2], [6,2],                  [13,2], [14,2], [15,2], [16,2], [17,2]]
    - [[2,3], [3,3], [4,3], [5,3], [6,3],                  [13,3], [14,3], [15,3], [16,3], [17,3]]
    - [                            [6,4], [7,4],   [12,4], [13,4]                                ]

  positions:
    - [[50.5,110.5], [100.5, 70.5], [150.5, 50.5], [200.5, 65.5], [250.5, 70.5],                              [450.5, 70.5], [500.5, 65.5], [550.5, 50.5], [600.5, 70.5], [650.5,110.5]]
    - [[50.5,160.5], [100.5,120.5], [150.5,100.5], [200.5,115.5], [250.5,120.5],                              [450.5,120.5], [500.5,115.5], [550.5,100.5], [600.5,120.5], [650.5,160.5]]
    - [[50.5,210.5], [100.5,170.5], [150.5,150.5], [200.5,165.5], [250.5,170.5],                              [450.5,170.5], [500.5,165.5], [550.5,150.5], [600.5,170.5], [650.5,210.5]]
    - [                                                        [230.5,225.5],  [290.5,245.5],   [410.5,245.5],   [470.5,225.5]                                                         ]

  hands:
    - [Left, Left, Left, Left, Left,                Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left,                Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left,                Right, Right, Right, Right, Right]
    - [                        Left, Left,   Right, Right                            ]

  fingers:
    - [Pinky, Ring,  Middle, Index, Index,                 Index, Index, Middle, Ring,  Pinky]
    - [Pinky, Ring,  Middle, Index, Index,                 Index, Index, Middle, Ring,  Pinky]
    - [Pinky, Ring,  Middle, Index, Index,                 Index, Index, Middle, Ring,  Pinky]
    - [                             Thumb, Thumb,   Thumb, Thumb,                            ]

  key_costs:
    - [20,  8,  6,  7, 10,           10,  7,  6,  8, 20]
    - [ 5,  3,  2,  2,  8,            8,  2,  2,  3,  5]
    - [11, 12,  9,  6, 15,           15,  6,  9, 12, 11]
    - [                 6,  2,    2,  6                ]

  unbalancing_positions:
    - [[0, 0.5], [0,   0], [0,  0], [0, 0.5], [1,    1],                  [-1,    1], [0, 0.5], [0, 0], [0,   0], [0, 0.5]]
    - [[0,   0], [0,   0], [0,  0], [0,   0], [1,    0],                  [-1,    0], [0,   0], [0, 0], [0,   0], [0,   0]]
    - [[0,   0], [0,   0], [0,  0], [0,   0], [1,   -1],                  [-1,   -1], [0,   0], [0, 0], [0,   0], [0,   0]]
    - [                                       [0,    0],  [0, 0], [0, 0], [0,   0]                                        ]

  symmetries:
    - [10, 11, 12, 13, 14,           14, 13, 12, 11, 10]
    - [16, 17, 18, 19, 20,           20, 19, 18, 17, 16]
    - [22, 23, 24, 25, 26,           26, 25, 24, 23, 22]
    - [                28, 29,   29, 28                ]

  finger_resting_positions:
    Left:
      Pinky: [50.5, 160.5]
      Ring: [100.5, 120.5]
      Middle: [150.5, 100.5]
      Index: [200.5, 115.5]
      Thumb: [290.5, 245.5]
    Right:
      Pinky: [650.5, 160.5]
      Ring: [600.5, 120.5]
      Middle: [550.5, 100.5]
      Index: [500.5, 115.5]
      Thumb: [410.5, 245.5]


  plot_template: |2
            ┌───┐                         ┌───┐
        ┌───┤ {{2}} ├───┬───┐         ┌───┬───┤ {{7}} ├───┐
    ┌───┤ {{1}} ├───┤ {{3}} │ {{4}} │         │ {{5}} │ {{6}} ├───┤ {{8}} ├───┐
    │ {{0}} ├───┤ {{12}} ├───┼───┤         ├───┼───┤ {{17}} ├───┤ {{9}} │
    ├───┤ {{11}} ├───┤ {{13}} │ {{14}} │         │ {{15}} │ {{16}} ├───┤ {{18}} ├───┤
    │ {{10}} ├───┤ {{22}} ├─━─┼───┤         ├───┼─━─┤ {{27}} ├───┤ {{19}} │
    ├───┤ {{21}} ├───┤ {{23}} │ {{24}} │         │ {{25}} │ {{26}} ├───┤ {{28}} ├───┤
    │ {{20}} ├───┘   └───┴───┘         └───┴───┘   └───┤ {{29}} │
    └───┘           ┌───┬───┐ ┌───┬───┐           └───┘
                    │ {{30}} │ {{31}} │ │ {{32}} │ {{33}} │
                    └───┴───┘ └───┴───┘


  plot_template_short: |2
    {{0}}{{1}}{{2}}{{3}}{{4}} {{5}}{{6}}{{7}}{{8}}{{9}}
    {{10}}{{11}}{{12}}{{13}}{{14}} {{15}}{{16}}{{17}}{{18}}{{19}}
    {{20}}{{21}}{{22}}{{23}}{{24}} {{25}}{{26}}{{27}}{{28}}{{29}}
       {{30}}{{31}} {{32}}{{33}}

base_layout:
  keys:
    # Row 1
    - - ["ż", "Ż"]
      - ["w", "W"]
      - ["f", "F"]
      - ["p", "P"]
      - ["g", "G"]
      - ["j", "J"]
      - ["l", "L"]
      - ["u", "U"]
      - ["y", "Y"]
      - ["ó", "Ó"]
    # Row 2 (home row)
    - - ["a", "A"]
      - ["r", "R"]
      - ["s", "S"]
      - ["t", "T"]
      - ["ń", "Ń"]
      - ["h", "H"]
      - ["n", "N"]
      - ["e", "E"]
      - ["i", "I"]
      - ["o", "O"]
    # Row 3
    - - ["ą", "Ą"]
      - ["x", "X"]
      - ["c", "C"]
      - ["v", "V"]
      - ["b", "B"]
      - ["ł", "Ł"]
      - ["m", "M"]
      - ["ę", "Ę"]
      - ["ś", "Ś"]
      - ["ć", "Ć"]
    # Row 4, containing the spacebar
      - ["k", "K"]
      - ["d", "D"]
      - [" " ]
      - ["z", "Z"]

  fixed_keys:
    - [ false, false, false, false, false,                  false, false, false, false, false]
    - [ false, false, false, false, false,                  false, false, false, false, false]
    - [ false, false, false, false, false,                  false, false, false, false, false]
    - [                             false, false,     true, false                            ]

  # for NeoLayoutGenerator:
  # layers that shall not be permutated (starting from 0)
  fixed_layers: []

  # for GroupedLayoutGenerator:
  # number of consecutive symbols from base layout to group together generating a layout
  grouped_layers: 2

  modifiers:
    - Left:
        type: hold
        value: [[12,4]]
      Right:
        type: hold
        value: [[12,4]]
